### ISSUE TITLE
KG: Bug | Daftar, Login| Placeholder textbox salah

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#240]
[ ]  Placeholder textbox masih menggunakan data akun orang lain.

Sebaiknya placeholdernya diganti menjadi petunjuk saja misalkan : “Isi Nama Lengkap dengan benar”
![image](https://github.com/magang-mknows/mknows-fe/assets/83324036/8def827a-59ce-43e6-a187-290cb43bc59d)

**Comment by maulanasdqn** [comment]
hmm okeh

**Comment by maulanasdqn** [comment]
solved
