### ISSUE TITLE
KG: Bug | Alert | Penulisan alert tidak konsisten

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#247]
- [ ] Alert pada halaman login dan daftar, sebaiknya menggunakan bahasa indonesia saja, agar user tidak kebingungan memahami isi dari alert, selain itu agar adanya konsistensi dalam penggunaan bahasa pada web kg.

<img width="415" alt="image" src="https://github.com/magang-mknows/mknows-fe/assets/83324036/113f3191-77d6-425b-b7f3-628e97099917">

**Comment by maulanasdqn** [comment]
itu dari BE nya ya, solved
