### ISSUE TITLE
KG: Bug | Daftar | Validasi Inputan user masih salah

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#250]
- [ ] Pada form pengisian kata sandi, tidak ada muncul alert bahwa user harus input password dengan karakter kuat, sementara setelah user klik button daftar, muncul  alert bahwa password is not strong enough, sehingga user harus input ulang kembali password dan akan menghabiskan waktu. 

Sebaiknya dicantumkan validasi password strength Meter untuk langsung mengevaluasi password berdasarkan sejumlah kriteria keamanan, seperti panjang karakter, penggunaan huruf besar dan kecil, angka dan karakter khusus lainnya. 

![image](https://github.com/magang-mknows/mknows-fe/assets/83324036/6fdf3d82-22ef-488e-8e79-5fc032b65628)

**Comment by maulanasdqn** [comment]
noted

**Comment by maulanasdqn** [comment]
![image](https://github.com/magang-mknows/mknows-fe/assets/53475078/c39234e0-382a-40dd-a2a6-d65b7c6f4f0f)
solved
