### ISSUE TITLE
KG: Bug | Login | Verfikasi Login akun baru masih error

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#251]
- [ ]  Setelah user berhasil mendaftarkan akun, website akan direct ke halaman login, dan tidak ada notif atau pop up bahwa user harus verfikasi email terlebih dahulu. Saat user login, akan muncul alert bahwa email belum di verifikasi. Sementara setelah dicek di email, tidak ada inbox untuk verifikasi email. 

![image](https://github.com/magang-mknows/mknows-fe/assets/83324036/b40f71d8-1ee6-494a-a48f-072d03058818)

**Comment by maulanasdqn** [comment]
itu mah salah BE mbak @heniernitaaa
