### ISSUE TITLE
CS | Bug UI | Hal.Dashboard

### ISSUE THREAD

**Issue by Jesica28AA** [magang-mknows/mknows-fe#276]
- [x] -	Untuk filter riwayat permintaan pada grafik track usia ini masih belum sesuai jika zoom chrome dengan 100%
- [ ] 
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/3b4b4a43-aee3-47d1-ba25-230406135c3b)

**Comment by mochilhamsyah17** [comment]
done
