### ISSUE TITLE
CS | Bug UI | Hal.Permintaan

### ISSUE THREAD

**Issue by Jesica28AA** [magang-mknows/mknows-fe#278]
- [x] #342
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/738d983e-f184-42f7-ba07-1e5e79414ccd)

- [x] Halaman Permintaan  Laporan: Berikan warna biru pada kata "Klik Disini" karena merupakan anchor text
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/ea9dcd72-cfca-4dee-a1aa-e83ab73af275)

- [x]  Halaman Permintaan -> Laporan: Warna Font untuk data kendala proses lebih baik hitam agar user dapat melihatnya lebih jelas
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/1ec3c2b6-39ef-47fe-aaf7-8605fdb98624)

- [x] Halaman Permintaan  Proses & Hasil: Untuk seluruh data tanggal diberikan tanggal, jam, menit dan detiknya
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/fb55bc7c-a84c-43a8-9b13-5c30277da93b)

**Comment by fnny04** [comment]
sementara link pembaharuannya ini ya https://mknows-fe-cs-git-feature-add-page-choice-f-a1e84f-magang-mknows.vercel.app/
