### ISSUE TITLE
CS | Bug UI | Semua Halaman

### ISSUE THREAD

**Issue by Jesica28AA** [magang-mknows/mknows-fe#281]
- [x] Di hapus saja bagian NIM, karena data berdasarkan NIM tidak ada
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/4961a823-7b74-438c-af3d-48a6bd155953)

- [x] Lebih baik filter dengan menggunakan jenis-jenis AI (filter Semua) dihapus saja, karena pada bagian data tidak ada dijelaskan dengan jenis AI apa
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/123586e9-7776-45cf-95fa-d6e469cee04f)

- [x] Tampilan kalender belum sesuai dengan design di figma
![image](https://github.com/magang-mknows/mknows-fe/assets/103129245/7e04e7ac-6227-42e2-ae00-54c948490cff)

**Comment by fnny04** [comment]
@Jesica28AA untuk sementara pembaharuan ui bisa liat di link ini ya untuk di tes lagi https://mknows-fe-cs-git-feature-add-page-choice-f-a1e84f-magang-mknows.vercel.app/dashboard/home
