### ISSUE TITLE
KG : Bug | Fitur Edit Profile | Text box email pada form edit profile belum bisa diisi

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#311]
- [ ]  Text box untuk inputan email oleh user masih belum bisa di klik atau disable

<img width="498" alt="image" src="https://github.com/magang-mknows/mknows-fe/assets/83324036/05df14e9-9420-4b98-a4c5-2ab226f5b3b2">

**Comment by maulanasdqn** [comment]
sudah solved ya silahkan di cek kembali @heniernitaaa

**Comment by heniernitaaa** [comment]
untuk field inputan email nya belum bisa diklik juga @maulanasdqn 

<img width="655" alt="image" src="https://github.com/magang-mknows/mknows-fe/assets/83324036/54c6d5ac-ccfd-4d76-85c3-348440174f11">
