### ISSUE TITLE
KG : Bug | Fitur Reset Password | Button Reset Password masih belum di develop

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#314]
- [ ]  Button Reset Password masih belum didevelop dan masih disable

<img width="517" alt="image" src="https://github.com/magang-mknows/mknows-fe/assets/83324036/04f280aa-7b64-4b70-9f5b-dec14a2d17bb">

**Comment by maulanasdqn** [comment]
![image](https://github.com/magang-mknows/mknows-fe/assets/53475078/ff2456a8-2c07-470b-aa8d-fdbf610d7691)
solved ya @heniernitaaa
