### ISSUE TITLE
CS | Bug UI | Hal. Dashboard

### ISSUE THREAD

**Issue by Jesica28AA** [magang-mknows/mknows-fe#470]
- [x] Tolong di samakan besar untuk setiap card berikut ini
<img width="960" alt="image" src="https://github.com/magang-mknows/mknows-fe/assets/103129245/79315098-8d16-42ad-aaa0-a164b7be2038">

**Comment by fnny04** [comment]
![bugqa](https://github.com/magang-mknows/mknows-fe/assets/79123882/0989f3ee-9fd3-4858-a8c6-302868c730ac)


udah dibenerin yaaaa :)
