### ISSUE TITLE
CS | Bug Function | Hal. Permintaan

### ISSUE THREAD

**Issue by Jesica28AA** [magang-mknows/mknows-fe#498]
- [x] Belum dapat melakukan Sort By A-Z ataupun Z-A
- [x] Belum dapat melakukan pencarian data pada box search
- [x] Belum dapat melakukan checklist untuk semua kolom checklist
- [x] Button Proses belum dapat digunakan

**Comment by fnny04** [comment]
check @Jesica28AA  designya memang ga sama tapi coba nnti aku minta ui nya sesuain atau aku yang mencari cara
