### ISSUE TITLE
KG: Bug | Diskusi Global| Field isi diskusi pada form diskusi baru masih terlalu kecil

### ISSUE THREAD

**Issue by heniernitaaa** [magang-mknows/mknows-fe#572]
- [x] pada form Buat Diskusi baru, filed isi diskusi masih terlalu kecil untuk inputannya, dan tampilan pada form diskusi baru ini masih terlalu monoton dan kurang menarik

<img width="402" alt="image" src="https://github.com/magang-mknows/mknows-fe/assets/83324036/e02a0e57-7720-415c-9606-22074719e193">

**Comment by fauzannmw** [comment]
done
